FROM @IMAGE@

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

ARG TARBALL

RUN dnf install -y --setopt=install_weak_deps=False \
                clang \
                clang-analyzer \
                curl \
                gcc \
                git-core \
                help2man \
                libpath_utils-devel \
                libtalloc-devel \
                meson \
                ninja-build \
                openssl-devel \
                pkgconf \
                popt-devel \
                redhat-rpm-config \
                ruby \
                rubygems \
                "rubygem(json)" \
                sudo \
                wget && \
    dnf -y clean all

