# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/fedora/sscg.spec

sync_changelog: true

upstream_package_name: sscg
upstream_tag_template: sscg-{version}
archive_root_dir_template: "{upstream_pkg_name}-{upstream_pkg_name}-{version}"

downstream_package_name: sscg

notifications:
  pull_request:
    successful_build: true


jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - centos-stream-8
    - epel-8
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - centos-stream-8
    - epel-8
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-all
