<<<<<<< HEAD
# See the documentation for more information:
# https://packit.dev/docs/configuration/

=======
---
downstream_package_name: sscg
>>>>>>> 85c8370 (downstream_package_name)
specfile_path: packaging/fedora/sscg.spec

sync_changelog: true

upstream_package_name: sscg
upstream_tag_template: sscg-{version}

downstream_package_name: sscg


notifications:
  pull_request:
    successful_build: false


jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - centos-stream-8
    - epel-8
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - centos-stream-8
    - epel-8
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-all

