# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: sscg.spec

# add or remove files that should be synced
files_to_sync:
    - sscg.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: sscg
# downstream (Fedora) RPM package name
downstream_package_name: sscg
# Tag format for versions
upstream_tag_template: sscg-{version}

actions:
  post-upstream-clone:
    # rawhide specfile will be the source of truth: we don't need to have the specfile upstream
    - curl -Lvso sscg.spec https://src.fedoraproject.org/rpms/sscg/raw/main/f/sscg.spec
  get-current-version:
    - cat sscg.version

jobs:
- job: copr_build
  trigger: pull_request
  targets:
    - fedora-all
    - fedora-all-aarch64
    - fedora-all-ppc64le
    - fedora-all-s390x
    - epel-10
    - epel-10-aarch64
    - epel-10-ppc64le
    - epel-10-s390x
    - epel-9
    - epel-9-aarch64
    - epel-9-ppc64le
    - epel-9-s390x

- job: tests
  trigger: pull_request
  targets:
    - fedora-all
    - epel-10
    - epel-9

- job: pull_from_upstream
  trigger: release
  dist_git_branches:
    - rawhide
