FROM @IMAGE@

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

ARG TARBALL

RUN yum -y install epel-release \
ifelse(eval(_RELEASE_ >= 8), 1, `dnl
    && yum -y install dnf-plugins-core \
    && yum config-manager --enable PowerTools \
')dnl
    && yum -y install \
	clang \
	git-core \
	help2man \
	meson \
	gcc \
	ninja-build \
	wget \
	curl \
	openssl \
	popt-devel \
	sudo \
	pkgconfig \
	redhat-rpm-config \
	ruby \
	rubygems \
	"rubygem(json)" \
	libtalloc-devel \
	libpath_utils-devel \
	openssl-devel \
    && yum -y clean all

