name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
#         https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1936975
#         - ubuntu-18.04
          - ubuntu-20.04
        compiler:
          - gcc
          - clang

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y meson pkgconf libssl-dev libpath-utils-dev libtalloc-dev help2man libpopt-dev ${{ matrix.compiler }}
        sudo apt install -y --no-install-recommends debhelper devscripts lintian
        # 18.04's debhelper is too old, we want to use compat level 12
        if grep -q 18.04 /etc/os-release; then
            sudo apt install -y -t bionic-backports debhelper
        fi

    - name: Configure build directory
      run: |
        CC=${{ matrix.compiler}} meson ${{ matrix.os }}

    - name: Build SSCG
      run: |
        ninja -C ${{ matrix.os }}

    - name: Run in-tree tests
      run: |
        meson test -t 5 --print-errorlogs -C ${{ matrix.os }}

    - name: Build Debian source package
      run: |
        set -ex
        mkdir deb
        # keep version number as 0 for upstream, to match debian/changelog
        git archive -o deb/sscg_0.orig.tar.gz --prefix sscg/ HEAD
        cd deb
        # unpack tar again to make sure the dist is complete and clean
        tar xf sscg_*.tar.gz
        cd sscg
        cp -r packaging/debian .

        # build source and binary package, with lintian
        debuild -e CC=${{ matrix.compiler}} -us -uc

    - name: Install built Debian binary package
      run: |
        sudo dpkg -i deb/sscg_*.deb

    - name: Smoke test installed package
      run: |
        cd /tmp/
        sscg
        openssl x509 -in service.pem -text
        openssl x509 -in ca.crt -text

  fedora:
    name: Fedora x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - 32
          - 33
          - 34
        compiler:
          - gcc
          - clang

    container:
      image: fedora:${{ matrix.release }}

    steps:
    - name: Identify the system
      run: |
        cat /etc/os-release

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf install -y meson pkgconf openssl-devel libpath_utils-devel libtalloc-devel help2man popt-devel ${{ matrix.compiler }}

    - name: Configure build directory
      run: |
        CC=${{ matrix.compiler}} meson fedora-${{ matrix.release }}

    - name: Build SSCG
      run: |
        ninja -C fedora-${{ matrix.release }}

    - name: Run in-tree tests
      run: |
        meson test -t 5 --print-errorlogs -C fedora-${{ matrix.release }}


  fedora_multiarch:
    name: Fedora non-x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          - ppc64le
          - s390x
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2.1.0
        name: Perform upstream tests

        with:
          arch: ${{ matrix.arch }}
          distro: fedora_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            dnf update -y --refresh
            dnf install -y meson pkgconf openssl-devel libpath_utils-devel libtalloc-devel help2man popt-devel ${{ matrix.compiler }}

          run: |
            CC=${{ matrix.compiler}} meson fedora-${{ matrix.arch }}
            meson test -t 10 --print-errorlogs -C fedora-${{ matrix.arch }}


  centos:
    name: CentOS
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        release:
          - 7
          - 8
        compiler:
          - gcc
          - clang
        exclude:
          - release: 7
            compiler: clang

    container:
      image: centos:${{ matrix.release }}

    steps:
    - name: Identify the system
      run: |
        cat /etc/os-release

    - name: Checkout SSCG code
      uses: actions/checkout@v2

    - name: Checkout popt subproject
      if: matrix.release == '7'
      uses: actions/checkout@v2
      with:
        repository: sgallagher/POPT
        path: subprojects/popt

    - name: Enable EPEL
      run: |
        yum -y install epel-release

    - name: Enable PowerTools
      if: matrix.release == '8'
      run: |
        yum -y install dnf-plugins-core
        yum config-manager --set-enabled powertools

    - name: Install OpenSSL 1.1 Development Libraries
      if: matrix.release == '7'
      run: |
        yum -y install openssl11-devel

    - name: Install build dependencies
      run: |
        yum install -y git-core glibc-devel openssl-devel meson pkgconf libpath_utils-devel libtalloc-devel help2man popt-devel ${{ matrix.compiler }}

    - name: Configure build directory
      run: |
        CC=${{ matrix.compiler}} meson --errorlogs centos-${{ matrix.release }} || cat centos-7/meson-logs/meson-log.txt

    - name: Build SSCG
      run: |
        ninja -C centos-${{ matrix.release }}

    - name: Run in-tree tests
      run: |
        meson test -t 5 --print-errorlogs -C centos-${{ matrix.release }}


  centos-stream:
    name: CentOS Stream
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      matrix:
        release:
          - 9
        compiler:
          - gcc
          - clang

    container:
      image: quay.io/centos/centos:stream9-development

    steps:
    - name: Identify the system
      run: |
        cat /etc/os-release

    - name: Checkout SSCG code
      uses: actions/checkout@v2

    - name: Enable CRB
      run: |
        yum -y install dnf-plugins-core
        yum config-manager --set-enabled crb

    - name: Add OpenSSL 3.0 Beta Repo
      working-directory: /etc/yum.repos.d
      run: |
        curl -O https://sgallagh.fedorapeople.org/repo/openssl3b/openssl3b.repo

    - name: Install build dependencies
      run: |
        yum install -y meson pkgconf-pkg-config openssl-devel libpath_utils-devel libtalloc-devel help2man popt-devel ${{ matrix.compiler }}

    - name: Configure build directory
      run: |
        CC=${{ matrix.compiler}} meson --errorlogs centos-stream-${{ matrix.release }} || ( cat centos-stream-${{ matrix.release }}/meson-logs/meson-log.txt && exit 1 )

    - name: Build SSCG
      run: |
        ninja -C centos-stream-${{ matrix.release }}

    - name: Run in-tree tests
      run: |
        meson test -t 5 --print-errorlogs -C centos-stream-${{ matrix.release }}
